### PR TITLE
AppVeyor builds for Windows

### PR DESCRIPTION
**Pull request by mlt**
I have AppVeyor setup at https://ci.appveyor.com/project/mlt_temporal_tables/acl for now. Perhaps, you could <del>add it to your account and</del> add a badge to readme. Apparently it is already [picked up](https://ci.appveyor.com/project/arkhipov/acl/). Did you set it up, or github is so smart?

P.S. I'm not quite happy with tests reporting within AppVeyor, but I think it should be okay for now.

### CODE REVIEW

**Comment by mlt** [comment]
Hold on with merging just yet! I want to add x86 support as apparently there is a demand at least for temporal_tables... so I'll use this as a test bed.

**Comment by mlt** [comment]
I'm done. For whatever reason downloads fail periodically. But those should be cached over time.

**Comment by arkhipov** [comment]
Thank you! You saved me hours of work.

**Comment by mlt** [comment]
Not a problem! Thanks for awesome extensions (I still have to master :yum: )!
I noticed you manually packaged releases and joined few versions (-/+). Is there a point to keep building for that many versions then? I was going to see how AppVeyor pushes artifacts to github. The tagged build for ACL was cancelled. And that for temporal_tables complained on missing authentication token.

**Comment by arkhipov** [comment]
Yes, there is. The Postgres codebase changes, so the extension might behave differently if a different version is running (personally, I would prefer if the tests were run against all supported versions). Besides, there are a few `#if`s in the extension code that could lead to different compilation results depending on the Postgres version.

**Pull request merged**
